### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by nishantjain91** [tmilewski/serverless-resources-validation-plugin#3]
On running the plugin,I am getting the following error `serverlessError: ValidationError: Invalid template property or properties [isFulfilled, isRejected]`

The reason for this is getResources is returning a json string which contains following data only
`{
     isFulfilled: false,
     isRejected: false
}`

**Comment by tmilewski** [comment]
@nishantjain91 Should be good now. Serverless is a fast-moving target.
